// src/性斗学园/战斗界面/project_-midnight-campus/components/CombatLog.tsx
import React, { useEffect, useRef, useState } from 'react';
import { CombatLogEntry } from '../types';
import { ChevronDown, ChevronUp, MessageSquare } from 'lucide-react';

interface CombatLogProps {
  logs: CombatLogEntry[];
}

const CombatLog: React.FC<CombatLogProps> = ({ logs }) => {
  const bottomRef = useRef<HTMLDivElement>(null);
  const [isExpanded, setIsExpanded] = useState(true);

  // Auto-scroll only when expanded
  useEffect(() => {
    if (isExpanded) {
      bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [logs, isExpanded]);

  return (
    <div
      className={`
      relative bg-black/40 backdrop-blur-md rounded-xl border border-white/10 shadow-inner overflow-hidden transition-all duration-300
      ${isExpanded ? 'h-48' : 'h-12'}
    `}
    >
      {/* Header / Toggle Bar */}
      <div
        onClick={() => setIsExpanded(!isExpanded)}
        className="absolute top-0 left-0 w-full h-8 bg-white/5 flex items-center justify-between px-3 cursor-pointer hover:bg-white/10 transition-colors z-10"
      >
        <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-widest">
          <MessageSquare size={12} />
          <span>战斗日志</span>
        </div>
        <div className="text-slate-400">{isExpanded ? <ChevronDown size={14} /> : <ChevronUp size={14} />}</div>
      </div>

      {/* Content Area */}
      <div className={`pt-10 pb-2 px-4 h-full overflow-y-auto ${!isExpanded ? 'opacity-50' : ''}`}>
        {/* If collapsed, show the last message in a specific way or just let the scroll hide it? 
             Better: when collapsed, just hide the list and maybe show a marquee or nothing.
             For this design, changing height is enough, but let's show the latest log if collapsed.
         */}

        {!isExpanded && logs.length > 0 && (
          <div className="absolute top-8 left-4 right-4 truncate text-sm text-slate-300">
            <span className="opacity-50 text-xs mr-2">[{logs[logs.length - 1].turn}]</span>
            {logs[logs.length - 1].message}
          </div>
        )}

        {/* Full List */}
        <div className={!isExpanded ? 'invisible' : ''}>
          {logs.length === 0 && <p className="text-slate-500 text-center italic mt-10">战斗即将开始...</p>}
          {logs.map(log => (
            <div
              key={log.id}
              className={`
                animate-slide-up 
                pb-1 border-b border-white/5 last:border-0 mb-1
                text-sm font-mono
                ${log.type === 'critical' ? 'text-yellow-400 font-bold' : ''}
                ${log.type === 'damage' ? 'text-red-300' : ''}
                ${log.type === 'heal' ? 'text-green-300' : ''}
                ${log.type === 'info' ? 'text-slate-300' : ''}
                `}
            >
              <span className="opacity-50 text-xs mr-2">[{log.turn}]</span>
              {log.message}
            </div>
          ))}
          <div ref={bottomRef} />
        </div>
      </div>
    </div>
  );
};

export default CombatLog;

// src/性斗学园/战斗界面/components/CombatLog.vue
<template>
  <div class="combat-log" :class="{ 'log-expanded': isExpanded }">
    <!-- 头部切换栏 -->
    <div class="log-header" @click="isExpanded = !isExpanded">
      <div class="log-title">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
        </svg>
        <span>战斗日志</span>
      </div>
      <div class="log-toggle">
        <svg
          v-if="isExpanded"
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
        <svg
          v-else
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path d="m18 15-6-6-6 6" />
        </svg>
      </div>
    </div>

    <!-- 折叠时显示最新日志 -->
    <div v-if="!isExpanded && logs.length > 0" class="log-preview">
      <span class="log-turn">[{{ logs[logs.length - 1].turn }}]</span>
      {{ logs[logs.length - 1].message }}
    </div>

    <!-- 展开的日志列表 -->
    <div class="log-content" :class="{ 'log-hidden': !isExpanded }">
      <p v-if="logs.length === 0" class="log-empty">战斗即将开始...</p>
      <div
        v-for="log in logs"
        :key="log.id"
        class="log-entry"
        :class="{
          'log-critical': log.type === 'critical',
          'log-damage': log.type === 'damage',
          'log-heal': log.type === 'heal',
          'log-info': log.type === 'info',
          'log-buff': log.type === 'buff',
        }"
      >
        <span class="log-turn">[{{ log.turn }}]</span>
        {{ log.message }}
      </div>
      <div ref="bottomRef"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref, watch } from 'vue';
import type { CombatLogEntry } from '../types';

const props = defineProps<{
  logs: CombatLogEntry[];
}>();

const isExpanded = ref(true);
const bottomRef = ref<HTMLDivElement | null>(null);

// 自动滚动到底部
watch(
  () => props.logs.length,
  () => {
    if (isExpanded.value) {
      nextTick(() => {
        bottomRef.value?.scrollIntoView({ behavior: 'smooth' });
      });
    }
  },
);
</script>

<style lang="scss" scoped>
.combat-log {
  position: relative;
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(12px);
  border-radius: 0.75rem;
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  transition: all 0.3s ease;
  height: 3rem;

  &.log-expanded {
    height: 12rem;
  }
}

.log-header {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 2rem;
  background: rgba(255, 255, 255, 0.05);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 0.75rem;
  cursor: pointer;
  z-index: 10;
  transition: background 0.2s;

  &:hover {
    background: rgba(255, 255, 255, 0.1);
  }
}

.log-title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.75rem;
  font-weight: 700;
  color: #94a3b8;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.log-toggle {
  color: #94a3b8;
}

.log-preview {
  position: absolute;
  top: 2rem;
  left: 1rem;
  right: 1rem;
  font-size: 0.875rem;
  color: #cbd5e1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.log-content {
  padding-top: 2.5rem;
  padding-bottom: 0.5rem;
  padding-left: 1rem;
  padding-right: 1rem;
  height: 100%;
  overflow-y: auto;

  &.log-hidden {
    visibility: hidden;
  }
}

.log-empty {
  color: #64748b;
  text-align: center;
  font-style: italic;
  margin-top: 2.5rem;
}

.log-entry {
  animation: slideUp 0.2s ease;
  padding-bottom: 0.25rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
  margin-bottom: 0.25rem;
  font-size: 0.875rem;
  font-family: ui-monospace, monospace;

  &:last-of-type {
    border-bottom: none;
  }
}

.log-turn {
  opacity: 0.5;
  font-size: 0.75rem;
  margin-right: 0.5rem;
}

.log-critical {
  color: #facc15;
  font-weight: 700;
}

.log-damage {
  color: #fca5a5;
}

.log-heal {
  color: #86efac;
}

.log-info {
  color: #cbd5e1;
}

.log-buff {
  color: #fbbf24;
  font-weight: 700;
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
