// src/性斗学园/开局/components/Step3_Attributes.vue
<template>
  <div class="animate-slide-up space-y-6">
    <div
      :class="[
        'flex justify-between items-center p-4 rounded-xl border',
        cheatMode
          ? 'bg-gradient-to-r from-yellow-900/50 to-orange-900/50 border-yellow-500/30'
          : 'bg-gradient-to-r from-indigo-900/50 to-purple-900/50 border-white/10',
      ]"
    >
      <div class="text-sm text-gray-300">
        <p>
          当前难度: <span class="text-white font-bold">{{ data.difficulty }}</span>
          <span v-if="cheatMode" class="ml-2 text-xs text-yellow-400">[作弊模式]</span>
        </p>
        <p class="text-xs text-gray-500 mt-1">初始点数: {{ totalPointsAvailable }}</p>
      </div>
      <div class="flex items-center gap-4">
        <!-- x10 切换按钮 -->
        <button
          @click="x10Mode = !x10Mode"
          :class="[
            'px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-300 border-2',
            x10Mode
              ? 'bg-secondary/20 border-secondary text-secondary shadow-lg shadow-pink-500/30'
              : 'bg-white/5 border-white/10 text-gray-400 hover:text-white hover:border-white/20',
          ]"
          title="点击切换x10模式"
        >
          <i :class="['fas', x10Mode ? 'fa-check-circle' : 'fa-times-circle', 'mr-2']"></i>
          <span class="font-mono">{{ x10Mode ? 'x10' : 'x1' }}</span>
        </button>
        <div class="text-right">
          <span class="block text-xs text-gray-400 uppercase tracking-wider">剩余点数</span>
          <span :class="['text-3xl font-bold', remaining === 0 ? 'text-gray-500' : 'text-secondary animate-pulse']">
            {{ remaining }}
          </span>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div
        v-for="stat in stats"
        :key="stat.path"
        class="flex items-center justify-between p-3 bg-white/5 rounded-xl border border-white/5 hover:border-white/10 transition-colors"
      >
        <div class="flex items-center gap-3">
          <div :class="['p-2 rounded-lg bg-black/20', stat.color]">
            <i :class="['fas', stat.icon]"></i>
          </div>
          <div>
            <span class="block text-sm font-medium text-gray-200">{{ stat.label }}</span>
            <span class="text-xs text-gray-500">{{ stat.costText }}</span>
          </div>
        </div>

        <div class="flex items-center gap-3">
          <button
            @click="handleStatChange(stat.path, -1)"
            :disabled="getCurrentValue(stat.path) <= getInitialValue(stat.path) || isUpdating"
            :class="[
              'w-8 h-8 flex items-center justify-center rounded-full text-gray-400 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed transition-all',
              x10Mode ? 'bg-white/10 hover:bg-white/20 border border-orange-500/30' : 'bg-white/5 hover:bg-white/10',
            ]"
            :title="x10Mode ? 'x10模式：点击一次减少10点' : '点击减少1点'"
          >
            <span v-if="x10Mode" class="text-xs font-bold">-10</span>
            <i v-else class="fas fa-minus text-sm"></i>
          </button>

          <span class="w-12 text-center font-mono font-bold text-lg text-white">
            {{ getCurrentValue(stat.path) }}
          </span>

          <button
            @click="handleStatChange(stat.path, 1)"
            :disabled="remaining <= 0 || isUpdating"
            :class="[
              'w-8 h-8 flex items-center justify-center rounded-full text-white shadow-lg hover:scale-110 active:scale-95 disabled:opacity-30 disabled:cursor-not-allowed disabled:transform-none transition-all',
              x10Mode
                ? 'bg-gradient-to-br from-orange-500 to-red-500 shadow-orange-500/30'
                : 'bg-secondary shadow-pink-500/20',
            ]"
            :title="x10Mode ? 'x10模式：点击一次增加10点' : '点击增加1点'"
          >
            <span v-if="x10Mode" class="text-xs font-bold">+10</span>
            <i v-else class="fas fa-plus text-sm"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { DIFFICULTY_POINTS, MAX_STATS } from '../constants';
import { CharacterAttributes, CharacterData, INITIAL_ATTRIBUTES } from '../types';
import { updateMvuVariable } from '../utils/mvu-helper';

const props = defineProps<{
  data: CharacterData;
  cheatMode?: boolean;
}>();

const emit = defineEmits<{
  (e: 'update-data', fields: Partial<CharacterData>): void;
}>();

const isUpdating = ref(false);
const x10Mode = ref(false);

// 作弊模式下使用999点，否则使用难度对应的点数
const totalPointsAvailable = computed(() => {
  if (props.cheatMode) return 999;
  return DIFFICULTY_POINTS[props.data.difficulty];
});

// 根据路径获取当前值
const getCurrentValue = (path: string): number => {
  const [category, key] = path.split('.');
  return (props.data.attributes[category as keyof CharacterAttributes] as any)?.[key] || 0;
};

// 根据路径获取初始值
const getInitialValue = (path: string): number => {
  const [category, key] = path.split('.');
  return (INITIAL_ATTRIBUTES[category as keyof CharacterAttributes] as any)?.[key] || 0;
};

// 计算已使用的点数（只计算可分配的6个属性）
const pointsUsed = computed(() => {
  let used = 0;
  const attrs = props.data.attributes;
  const init = INITIAL_ATTRIBUTES;

  // 确保所有值都存在，否则使用0
  const getVal = (obj: any, path: string[], fallback: number) => {
    let val = obj;
    for (const key of path) {
      val = val?.[key];
      if (val === undefined) return fallback;
    }
    return val ?? fallback;
  };

  // 角色基础 - 等级
  used += (getVal(attrs, ['角色基础', '_等级'], 1) - getVal(init, ['角色基础', '_等级'], 1)) * 1;
  // 核心状态 - 潜力（使用 Math.round 避免浮点数精度问题）
  const potentialDiff = getVal(attrs, ['核心状态', '_潜力'], 5.0) - getVal(init, ['核心状态', '_潜力'], 5.0);
  used += Math.round(potentialDiff * 10) * 2; // 0.1潜力 = 2点，先乘10取整再乘2避免浮点误差
  // 核心状态 - 基础魅力
  used += (getVal(attrs, ['核心状态', '$基础魅力'], 10) - getVal(init, ['核心状态', '$基础魅力'], 10)) * 1;
  // 核心状态 - 基础幸运
  used += (getVal(attrs, ['核心状态', '$基础幸运'], 10) - getVal(init, ['核心状态', '$基础幸运'], 10)) * 1;
  // 核心状态 - 最大耐力和最大快感
  used += (getVal(attrs, ['核心状态', '$最大耐力'], 100) - getVal(init, ['核心状态', '$最大耐力'], 100)) / 5;
  used += (getVal(attrs, ['核心状态', '$最大快感'], 100) - getVal(init, ['核心状态', '$最大快感'], 100)) / 5;

  return Math.max(0, Math.ceil(used));
});

const remaining = computed(() => totalPointsAvailable.value - pointsUsed.value);

// 可分配的属性列表（只有6个可分配属性）
const stats = [
  {
    path: '角色基础._等级',
    label: '初始等级',
    icon: 'fa-arrow-trend-up',
    color: 'text-yellow-400',
    costText: '1点 = 1级',
  },
  { path: '核心状态._潜力', label: '潜力资质', icon: 'fa-star', color: 'text-purple-400', costText: '2点 = 0.1潜力' },
  {
    path: '核心状态.$最大耐力',
    label: '最大耐力',
    icon: 'fa-shield-halved',
    color: 'text-green-400',
    costText: '1点 = 5耐力',
  },
  { path: '核心状态.$最大快感', label: '最大快感', icon: 'fa-heart', color: 'text-pink-400', costText: '1点 = 5快感' },
  {
    path: '核心状态.$基础魅力',
    label: '基础魅力',
    icon: 'fa-face-grin-hearts',
    color: 'text-rose-400',
    costText: '1点 = 1魅力',
  },
  { path: '核心状态.$基础幸运', label: '基础幸运', icon: 'fa-clover', color: 'text-cyan-400', costText: '1点 = 1幸运' },
];

const handleStatChange = async (path: string, delta: number) => {
  if (isUpdating.value) return;

  const [category, key] = path.split('.');

  // 计算实际的变化倍数
  const multiplier = x10Mode.value ? 10 : 1;
  const actualDelta = delta * multiplier;

  let cost = 1;
  let valueChange = actualDelta;

  // 根据属性类型计算成本和变化值
  if (path === '核心状态.$最大耐力' || path === '核心状态.$最大快感') {
    cost = 1;
    valueChange = actualDelta * 5;
  } else if (path === '核心状态._潜力') {
    cost = 2;
    valueChange = actualDelta * 0.1;
  }

  // 计算总成本
  const totalCost = cost * multiplier;

  // 检查剩余点数是否足够
  if (delta > 0 && remaining.value < totalCost) return;

  const currentVal = getCurrentValue(path);
  const maxVal = MAX_STATS[path as keyof typeof MAX_STATS] || 9999;
  const minVal = getInitialValue(path);

  // 计算新值
  let newVal = currentVal + valueChange;

  // 如果超过上限，调整到上限
  if (newVal > maxVal) {
    newVal = maxVal;
    // 重新计算实际使用的点数
    const actualValueChange = newVal - currentVal;
    if (path === '核心状态.$最大耐力' || path === '核心状态.$最大快感') {
      valueChange = actualValueChange;
    } else if (path === '核心状态._潜力') {
      valueChange = actualValueChange;
    } else {
      valueChange = actualValueChange;
    }
  }

  // 如果低于下限，调整到下限
  if (newVal < minVal) {
    newVal = minVal;
    valueChange = newVal - currentVal;
  }

  if (path === '核心状态._潜力') newVal = parseFloat(newVal.toFixed(1));

  if (newVal <= maxVal && newVal >= minVal) {
    isUpdating.value = true;

    try {
      // 更新本地状态
      const newAttributes = { ...props.data.attributes };
      const categoryObj = { ...newAttributes[category as keyof CharacterAttributes] } as any;
      categoryObj[key] = newVal;
      newAttributes[category as keyof CharacterAttributes] = categoryObj as any;

      // 先更新本地状态（立即反馈）
      emit('update-data', {
        attributes: newAttributes,
      });

      // 然后实时更新 MVU 变量
      await updateMvuVariable(path, newVal, `角色创建：${delta > 0 ? '增加' : '减少'}${Math.abs(valueChange)}`);
    } catch (error) {
      console.error('更新失败:', error);
    } finally {
      isUpdating.value = false;
    }
  }
};
</script>

<style lang="scss" scoped></style>

// src/性斗学园/开局/ethereal-academy-rpg/components/Step3_Attributes.tsx
import React, { useMemo } from 'react';
import { CharacterData, GameAttributes, INITIAL_ATTRIBUTES } from '../types';
import { DIFFICULTY_POINTS, MAX_STATS } from '../constants';
import { Plus, Minus, Zap, Heart, Star, Sparkles, TrendingUp, Shield } from 'lucide-react';

interface Props {
  data: CharacterData;
  updateData: (fields: Partial<CharacterData>) => void;
}

const Step3_Attributes: React.FC<Props> = ({ data, updateData }) => {
  const totalPointsAvailable = DIFFICULTY_POINTS[data.difficulty];

  // Calculate points used based on difference from INITIAL_ATTRIBUTES
  // Cost Logic:
  // Level: 1 pt = 1 level
  // Potential: 5 pts = 0.1 potential (Expensive!) -> Let's make it 10 pts = 0.5 potential
  // Charm/Luck: 1 pt = 1 val
  // Max Stamina/Pleasure: 1 pt = 5 val

  const pointsUsed = useMemo(() => {
    let used = 0;
    used += (data.attributes._等级 - INITIAL_ATTRIBUTES._等级) * 1;
    used += (data.attributes.$潜力 - INITIAL_ATTRIBUTES.$潜力) * 20; // 0.1 costs 2 points essentially
    used += (data.attributes._魅力 - INITIAL_ATTRIBUTES._魅力) * 1;
    used += (data.attributes._幸运 - INITIAL_ATTRIBUTES._幸运) * 1;
    used += (data.attributes._最大耐力 - INITIAL_ATTRIBUTES._最大耐力) / 5;
    used += (data.attributes._最大快感 - INITIAL_ATTRIBUTES._最大快感) / 5;
    return Math.max(0, Math.ceil(used));
  }, [data.attributes]);

  const remaining = totalPointsAvailable - pointsUsed;

  const handleStatChange = (key: keyof GameAttributes, delta: number) => {
    let cost = 1;
    let valueChange = delta;

    if (key === '_最大耐力' || key === '_最大快感') {
      cost = 1;
      valueChange = delta * 5;
    } else if (key === '$潜力') {
      cost = 2; // 2 points for 0.1 potential
      valueChange = delta * 0.1;
    }

    // Check if we can afford it (if adding)
    if (delta > 0 && remaining < cost) return;

    const currentVal = data.attributes[key];
    const maxVal = MAX_STATS[key as keyof typeof MAX_STATS] || 9999;
    const minVal = INITIAL_ATTRIBUTES[key];

    // Precision handling for floats
    let newVal = currentVal + valueChange;
    if (key === '$潜力') newVal = parseFloat(newVal.toFixed(1));

    if (newVal <= maxVal && newVal >= minVal) {
      updateData({
        attributes: {
          ...data.attributes,
          [key]: newVal,
        },
      });
    }
  };

  const StatRow = ({
    label,
    statKey,
    icon: Icon,
    color,
    costText,
  }: {
    label: string;
    statKey: keyof GameAttributes;
    icon: any;
    color: string;
    costText: string;
  }) => (
    <div className="flex items-center justify-between p-3 bg-white/5 rounded-xl border border-white/5 hover:border-white/10 transition-colors">
      <div className="flex items-center gap-3">
        <div className={`p-2 rounded-lg bg-black/20 ${color}`}>
          <Icon size={18} />
        </div>
        <div>
          <span className="block text-sm font-medium text-gray-200">{label}</span>
          <span className="text-xs text-gray-500">{costText}</span>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <button
          onClick={() => handleStatChange(statKey, -1)}
          disabled={data.attributes[statKey] <= INITIAL_ATTRIBUTES[statKey]}
          className="w-8 h-8 flex items-center justify-center rounded-full bg-white/5 text-gray-400 hover:bg-white/10 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed transition-all"
        >
          <Minus size={14} />
        </button>

        <span className="w-12 text-center font-mono font-bold text-lg text-white">{data.attributes[statKey]}</span>

        <button
          onClick={() => handleStatChange(statKey, 1)}
          disabled={remaining <= 0} // Simplify check, real check in handler
          className="w-8 h-8 flex items-center justify-center rounded-full bg-secondary text-white shadow-lg shadow-pink-500/20 hover:scale-110 active:scale-95 disabled:opacity-30 disabled:cursor-not-allowed disabled:transform-none transition-all"
        >
          <Plus size={14} />
        </button>
      </div>
    </div>
  );

  return (
    <div className="animate-slide-up space-y-6">
      <div className="flex justify-between items-center bg-gradient-to-r from-indigo-900/50 to-purple-900/50 p-4 rounded-xl border border-white/10">
        <div className="text-sm text-gray-300">
          <p>
            当前难度: <span className="text-white font-bold">{data.difficulty}</span>
          </p>
          <p className="text-xs text-gray-500 mt-1">初始点数: {totalPointsAvailable}</p>
        </div>
        <div className="text-right">
          <span className="block text-xs text-gray-400 uppercase tracking-wider">剩余点数</span>
          <span className={`text-3xl font-bold ${remaining === 0 ? 'text-gray-500' : 'text-secondary animate-pulse'}`}>
            {remaining}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <StatRow label="初始等级" statKey="_等级" icon={TrendingUp} color="text-yellow-400" costText="1点 = 1级" />
        <StatRow label="潜力资质" statKey="$潜力" icon={Star} color="text-purple-400" costText="2点 = 0.1潜力" />
        <StatRow label="最大耐力" statKey="_最大耐力" icon={Shield} color="text-green-400" costText="1点 = 5耐力" />
        <StatRow label="最大快感" statKey="_最大快感" icon={Heart} color="text-pink-400" costText="1点 = 5快感" />
        <StatRow label="个人魅力" statKey="_魅力" icon={Sparkles} color="text-rose-400" costText="1点 = 1魅力" />
        <StatRow label="幸运值" statKey="_幸运" icon={Zap} color="text-cyan-400" costText="1点 = 1幸运" />
      </div>
    </div>
  );
};

export default Step3_Attributes;
